### ISSUE TITLE
JSON Array cannot be used as root element

### ISSUE THREAD

**Issue by Faltenreich** [mirrajabi/okhttp-json-mock#3]
First of all, I would like to thank you for this awesome and very convenient library!
It makes perfect sense in our emerging application since our API is still under development.

I have an endpoint that responds with a JSON array:
`[ { ... }, { ... }, ... ]`

I would like to reuse this exact same JSON from the API, but currently I have to adjust these responses before I copy them into the assets in order to match your specification:
`{
  "status": 200,
  "response": {
    "items": <actual array from above>
  }
}`

Otherwise I get the following IllegalStateException from GSON, since it expects an object as defined in the MockedResponse.java of your library:
`Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $`

I would like to ditch the surrounding JSON object and parse only the array.
Is this possible?

**Comment by mirrajabi** [comment]
Hi,
I like the idea of the actual response being the root, but, It is not possible to achieve that with this library. I wanted it to be more general, so if in future I wanted to add another field like `status` it would be easier. but for your usecase, what you can do is making a clone of the project and changing the file-finding and node-finding logic of `intercept` function in [OkHttpMockInterceptor.java](https://github.com/mirrajabi/okhttp-json-mock/blob/c03a11b79e282b95fb7814e96e1acccb2c14b60d/okhttpjsonmock/src/main/java/ir/mirrajabi/okhttpjsonmock/OkHttpMockInterceptor.java#L68) to match your needs. and for status message you can put all 400 messages in a folder called 400 or something like this. also If you have a good idea to make the usage of the library more convenient to everyone, I would appreciate it because I can't think of a better solution right now.

**Comment by Faltenreich** [comment]
Hello @mirrajabi, thank you for your super-quick response! 
We are currently subclassing OkHttpMockInterceptor.java to override its intercept() method - even though we have to keep track of some properties, since they are private. Adjusting the original class makes perfect sense and we will consider this recommendation as long if it meets our schedule.
You may close this issue or keep it open if there are plans to adjust the library on your own in the near future.
Have a nice day and best regards from Germany!
